/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.1/samples
 */
plugins {
    id("java")
}

group = "org.phase01"
version = "1.0.0"

repositories {
    mavenCentral()
    google()
    maven("https://jitpack.io")
}

dependencies {
    implementation("org.apache.commons:commons-lang3:3.18.0")
    // 💡 1. JUnit 5 API: Needed for @Test, Assertions, etc.
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.10.0")

    // 💡 2. JUnit 5 ENGINE: Needed for Gradle to execute the tests.
    // This is the most likely missing piece causing the NullPointerException.
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.10.0")
}

tasks.test {
    useJUnitPlatform()
}